import { readFileSync, writeFileSync } from 'fs'

const css = readFileSync('./dist/tailwind.css', 'utf-8')
const escaped = css.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$')
writeFileSync(
  './src/tailwindCss.ts',
  `// Auto-generated by scripts/build-css.mjs — do not edit manually\nexport const TAILWIND_CSS = \`${escaped}\`\n`
)
console.log(`Generated src/tailwindCss.ts (${css.length} bytes)`)
